### ISSUE TITLE
Buttons need margin on top

### ISSUE THREAD

**Issue by tzohpilotl** [aldompe95/MHTASK3#11]
Hi, I noticed that the Get Distance, Delete Markers and Save Markers buttons are too close to the map and the street view. Some space there would look nice!

**Comment by aldompe95** [comment]
agree with that, i can do that in a few minutes

**Comment by tzohpilotl** [comment]
Check #12

**Comment by ulisesac4** [comment]
Buttons are now in another card container and it looks great, issue resolved ;)
